name: Create branch
on:
  # to be run once every 3 weeks for a 7.yy.0 release, so we can get a stable 7.yy.x branch for use by downstream consumers
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to create. Should be in format 7.yy.x'
        required: true
      branchfrom:
        description: 'The source branch from which to branch, eg., main'
        default: 'main'
      forceflag:
        description: 'To force creation of .x branch, use --force flag here'
        default: ''
jobs:
  build:
    name: Create branch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Create branch
        run: |
          git config --global user.name "Mykhailo Kuznietsov"
          git config --global user.email "mkuznets@redhat.com"
          curl https://raw.githubusercontent.com/eclipse-che/che-release/main/make-branch.sh | bash -s -- \
          --branch ${{ github.event.inputs.branch }} \
          --branchfrom ${{ github.event.inputs.branchfrom }} \
          --repo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
          ${{ github.event.inputs.forceflag }}
