#
# Copyright (c) 2019-2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Configbump Next Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches: [ main ]
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout configmump source code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to quay.io
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
    - id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build and push both short SHA tag and next tag
      uses: docker/build-push-action@v3
      with:
        file: build/dockerfiles/Dockerfile
        platforms: linux/amd64,linux/ppc64le,linux/arm64
        push: true
        tags: |
          quay.io/che-incubator/configbump:next
          quay.io/che-incubator/configbump:${{ steps.vars.outputs.sha_short }}
